### PR TITLE
Updated composer.json kriswallsmith/buzz requirement version

### PR DESCRIPTION
**Pull request by smoya**
Update kriswallsmith/buzz requirements version to <=0.7

### CODE REVIEW

**Comment by smoya** [comment]
Important for bundles that require newest 'buzz' version.

**Comment by gentisaliu** [comment]
I can reinforce this request. 

I am trying to install the HWIOAuthBundle (https://github.com/hwi/HWIOAuthBundle) which requires kriswallsmith/buzz >= 0.7 but it conflicts with the GoogleGeolocationBundle's kriswallsmith/buzz <= 0.5 requirement.

Please fix this.

**Comment by gentisaliu** [comment]
Others are having similar problems because of this as well:

http://stackoverflow.com/questions/15256416/symfony2-how-solve-two-bundles-requirements-conflicts-when-using-composer

Please consider.

**Comment by dsyph3r** [comment]
Thanks for the info, I haven't worked on this bundle for a long time. What version of buzz should this be upgraded to?

**Comment by gentisaliu** [comment]
Version 0.9 is the current version. I would change its composer.json
requirement to >= 0.9 . Thanks for your quick reaction.

**Comment by dsyph3r** [comment]
OK, no problem, I'll sort out this evening

**Comment by dsyph3r** [comment]
Version set to >=0.9 https://github.com/dsyph3r/GoogleGeolocationBundle/commit/22e9045c1ab290f0b6329f211679eda7394d4205

Hope this helps

**Comment by gentisaliu** [comment]
Thank you. I can only test this tomorrow at work and I'll let you know.

**Comment by dsyph3r** [comment]
Ok great, any problems let me know

**Comment by gentisaliu** [comment]
I can confirm that the bundle works without problems after updating to the latest Buzz version.

**Comment by dsyph3r** [comment]
Brilliant, thanks for your help

**Pull request closed without merging**
